#!/bin/bash

RESOURCEDIR="/opt/minecraft/.mc-resources/plugins"
PLUGINDIR="/opt/minecraft/mc-main/plugins"

if [ "$#" -ne 1 ]
then
	echo "Error: No argument given!"
  	echo "Usage: $ plugin-bump \"WorldGuard-4.9b482\""
  	exit 1
fi

if [[ ${1} == "resources" ]]; then
	ls -al ${RESOURCEDIR} | tail -n +4 | awk '{ print $9" "$10" "$11 }'
elif [[ ${1} == "server" ]]; then
	ls -al ${PLUGINDIR} | tail -n +4 | awk '{ print $9" "$10" "$11 }'
else
	echo "Error: only \"server\" and \"resources\" are valid arguments!"
	exit 1
fi