#!/bin/bash

PLUGINDIR="/opt/minecraft/.mc-resources/plugins"
SERVERDIR="/opt/minecraft/mc-main/plugins"

if [ "$#" -ne 1 ]
then
	echo "Error: No argument given!"
  	echo "Usage: $ plugin-up \"WorldGuard-latest.jar\""
  	exit 1
fi

if [ ! -L "${PLUGINDIR}/${1}" ]
then
    echo "Error: Couldn't find plugin-link \"${PLUGINDIR}/${1}\""
   	exit 1
fi

if [ -f "${SERVERDIR}/${1}" ]; then
	echo "Info: \"${SERVERDIR}/${1}\" already exists."
	MD51=`md5sum ${PLUGINDIR}/${1} | awk '{ print $1 }'`
	MD52=`md5sum ${SERVERDIR}/${1} | awk '{ print $1 }'`
	if [[ "${MD51}" == "${MD52}" ]]; then
		echo "Error: Checksum of \"${SERVERDIR}/${1}\" and \"${PLUGINDIR}/${1}\" are the same. Abbort."
	   	exit 1
	fi
fi

ln -sf "${PLUGINDIR}/${1}" "${SERVERDIR}/${1}"