#!/bin/bash

SERVERDIR="/opt/minecraft/mc-main/plugins"

if [ "$#" -ne 1 ]
then
	echo "Error: No argument given!"
  	echo "Usage: $ plugin-up \"WorldGuard-latest.jar\""
  	exit 1
fi

if [ ! -L "${SERVERDIR}/${1}" ]
then
    echo "Error: Couldn't find plugin-link \"${SERVERDIR}/${1}\""
   	exit 1
fi

read -p "Are you sure to remove \"${SERVERDIR}/${1}\"? [Y/n] " REPLY

if [ -z "$REPLY" ]; then
    REPLY=Y
fi

case "$REPLY" in
    Y*|y*)
        unlink "${SERVERDIR}/${1}"
        echo "Info: plugin \"${1}\" successfully removed."
        exit 0
        ;;
    N*|n*)
	    echo "Warning: Removal of \"${1}\" abborted... "    
        exit 1
        ;;
esac
