#!/bin/bash

PLUGINDIR="/opt/minecraft/.mc-resources/plugins"
PREFIXFORMAT="_latest"

if [ "$#" -ne 1 ]
then
	echo "Error: No argument given!"
  	echo "Usage: $ plugin-bump \"WorldGuard-4.9b482\""
  	exit 1
fi

if [ ! -f "${PLUGINDIR}/${1}" ]
then
    echo "Error: Couldn't find plugin \"${PLUGINDIR}/${1}\""
   	exit 1
fi

PLUGINNAME="${1%_*}"
VERSION="${1#*_}"

if [[ "${PLUGINNAME}" != "${1}" ]]; then
	ln -sf "${PLUGINDIR}/${1}" "${PLUGINDIR}/${PLUGINNAME}${PREFIXFORMAT}.jar"
fi