#!/bin/bash

SERVERDIR="/opt/minecraft/mc-main/plugins"

if [ "$#" -ne 1 ]
then
	echo "Error: No argument given!"
  	echo "Usage: $ plugin-up \"WorldGuard-latest.jar\""
  	exit 1
fi

if [ ! -L "${SERVERDIR}/${1}" ]
then
    echo "Error: Couldn't find plugin-link \"${SERVERDIR}/${1}\""
   	exit 1
fi

read -p "Are you sure to remove \"${SERVERDIR}/${1}\"? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    unlink "${SERVERDIR}/${1}"
fi

